name: brainbd
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  sms_autofill: ^2.3.1
  intl: ^0.18.0
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  firebase_app_check: ^0.2.1+18
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700


