// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBQHvM9HXCCduhJnD8WbzxOWQ4kP0JXE',
    appId: '1:951497628287:web:48e0686c41010670df7d4a',
    messagingSenderId: '951497628287',
    projectId: 'brain-buddies-b8bf4',
    authDomain: 'brain-buddies-b8bf4.firebaseapp.com',
    storageBucket: 'brain-buddies-b8bf4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVq6e6kLHq7Xk1rHK6rXueOGDGwewG-Zw',
    appId: '1:951497628287:android:32fcf2eb2428fbc3df7d4a',
    messagingSenderId: '951497628287',
    projectId: 'brain-buddies-b8bf4',
    storageBucket: 'brain-buddies-b8bf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrE5S9VDnTUfgPdsbDagYpHukCsJ9DAVs',
    appId: '1:951497628287:ios:1acbccd4ba7edc04df7d4a',
    messagingSenderId: '951497628287',
    projectId: 'brain-buddies-b8bf4',
    storageBucket: 'brain-buddies-b8bf4.appspot.com',
    iosBundleId: 'com.brainbd.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrE5S9VDnTUfgPdsbDagYpHukCsJ9DAVs',
    appId: '1:951497628287:ios:229030746e42af2bdf7d4a',
    messagingSenderId: '951497628287',
    projectId: 'brain-buddies-b8bf4',
    storageBucket: 'brain-buddies-b8bf4.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLBQHvM9HXCCduhJnD8WbzxOWQ4kP0JXE',
    appId: '1:951497628287:web:62b6e17c40a8ca53df7d4a',
    messagingSenderId: '951497628287',
    projectId: 'brain-buddies-b8bf4',
    authDomain: 'brain-buddies-b8bf4.firebaseapp.com',
    storageBucket: 'brain-buddies-b8bf4.appspot.com',
  );
}
